### ISSUE TITLE
crash and pod restart

### ISSUE THREAD

**Issue by randallt** [wavefrontHQ/wavefront-collector-for-kubernetes#123]
I just upgraded to v1.3.2 yesterday to try to improve memory utilization. I had been having frequent pod restarts, possibly due to reaching pod memory limits. After the upgrade it is looking much better, but I did have a couple restarts overnight. I got the log of the last one, and it ended with the following:

```
W0406 10:45:18.445204       1 reflector.go:302] github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/discovery/pod.go:75: watch of *v1.Pod ended with: too old resource version: 714294048 (714295435)
E0406 10:45:19.454336       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x16ab980), concrete:(*runtime._type)(0x1761060), asserted:(*runtime._type)(0x18b8fc0), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod)
goroutine 142 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x16ee820, 0xc00142ac00)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x16ee820, 0xc00142ac00)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/discovery.newPodHandler.func3(0x1761060, 0xc001299920)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/discovery/pod.go:38 +0x165
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:209
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x400, 0xc, 0x0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:609 +0x166
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000429e18, 0x7fbc28922680, 0xc000236640)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:601 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000236760)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000429f60, 0xdf8475800, 0x0, 0x1, 0xc000561b00)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00025ae00)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:599 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0005bc140, 0xc00044e120)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x65
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod [recovered]
	panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod

goroutine 142 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x16ee820, 0xc00142ac00)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/discovery.newPodHandler.func3(0x1761060, 0xc001299920)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/discovery/pod.go:38 +0x165
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:209
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x400, 0xc, 0x0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:609 +0x166
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00021fe18, 0x7fbc28922680, 0xc000236640)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:601 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000236760)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00021ff60, 0xdf8475800, 0x0, 0x1, 0xc000561b00)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00025ae00)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:599 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0005bc140, 0xc00044e120)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x65
```
Please let me know if I should enable debug (and how to enable it), to get more information.

**Comment by randallt** [comment]
This happened again in two of my environments last night. Stack looks the same.

**Comment by JSchuenke** [comment]
Hey @randallt! Thanks for the heads up. Looking into this now. To enable debug, you'll pass a flag to the collector as a command line option. You'll have to edit the daemonset/deployment and add the flag depending on how you deployed. 

More info on the flag: https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/master/docs/configuration.md#flags

This is where you can add the flag in the daemonset: https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/master/deploy/kubernetes/5-collector-daemonset.yaml#L32

You can set this as a parameter if you deployed with helm. Listed here: https://github.com/wavefrontHQ/helm/tree/master/wavefront#parameters

**Comment by randallt** [comment]
I've added debug to my logs. Will add any new debug output that looks related to a crash/restart here.

**Comment by randallt** [comment]
I got an occurrence with debug enabled, just for reference. Looks like it was handling a pod at the time:
```
time="2021-04-09T14:50:13Z" level=debug msg="handling resource" kind=pod name=aws-ebs-csi-driver-node-tp6dp namespace=openshift-cluster-csi-drivers
time="2021-04-09T14:50:13Z" level=debug msg="prometheus scrape=false for pod=aws-ebs-csi-driver-node-tp6dp"
time="2021-04-09T14:50:13Z" level=debug msg="no endpoint changes for openshift-cluster-csi-drivers-pod-aws-ebs-csi-driver-node-tp6dp"
time="2021-04-09T14:50:13Z" level=debug msg="handling resource" kind=pod name=multus-w9kmb namespace=openshift-multus
time="2021-04-09T14:50:13Z" level=debug msg="prometheus scrape=false for pod=multus-w9kmb"
time="2021-04-09T14:50:13Z" level=debug msg="no endpoint changes for openshift-multus-pod-multus-w9kmb"
time="2021-04-09T14:50:13Z" level=debug msg="handling resource" kind=pod name=ct-broadscan-query-deployment-c7b948785-knkmw namespace=ct-broadscan-query
E0409 14:50:13.353464       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x16ab980), concrete:(*runtime._type)(0x1761060), asserted:(*runtime._type)(0x18b8fc0), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod)
goroutine 141 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x16ee820, 0xc000fa57d0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x16ee820, 0xc000fa57d0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/discovery.newPodHandler.func3(0x1761060, 0xc000457b40)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/discovery/pod.go:38 +0x165
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:209
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0x0, 0x0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:609 +0x166
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00061ce18, 0x449b3f, 0xc0005daf60)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:601 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005daf60)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00061cf60, 0xdf8475800, 0x0, 0x1, 0xc0005a16e0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000622200)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:599 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0005cce60, 0xc000503100)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x65
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod [recovered]
	panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod

goroutine 141 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x16ee820, 0xc000fa57d0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/discovery.newPodHandler.func3(0x1761060, 0xc000457b40)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/discovery/pod.go:38 +0x165
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:209
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0x0, 0x0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:609 +0x166
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00058fe18, 0x449b3f, 0xc0005daf60)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:601 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005daf60)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00058ff60, 0xdf8475800, 0x0, 0x1, 0xc0005a16e0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000622200)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:599 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0005cce60, 0xc000503100)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x65
```
Looks like the linked fix already addresses this.
