### ISSUE TITLE
Fatal errors: concurrent map write and concurrent map write/iteration

### ISSUE THREAD

**Issue by elenatomlinson** [wavefrontHQ/wavefront-collector-for-kubernetes#60]
We are noticing fatal errors when deploying the Wavefront Collector `1.0.8` with a single sink to a Wavefront proxy:

```A 2020-02-24T22:05:03.752206563Z time="2020-02-24T22:05:03Z" level=info msg="Querying source" name=telegraf_swap_plugin_source
 
A 2020-02-24T22:05:03.753906250Z time="2020-02-24T22:05:03Z" level=info msg="Querying source" name=telegraf_cpu_plugin_source
 
A 2020-02-24T22:05:03.755173921Z time="2020-02-24T22:05:03Z" level=info msg="Querying source" name=telegraf_disk_plugin_source
 
A 2020-02-24T22:05:03.757854461Z time="2020-02-24T22:05:03Z" level=info msg="Querying source" name=telegraf_diskio_plugin_source
 
A 2020-02-24T22:05:03.760203123Z time="2020-02-24T22:05:03Z" level=info msg="Querying source" name=telegraf_system_plugin_source
 
A 2020-02-24T22:05:03.762502431Z time="2020-02-24T22:05:03Z" level=info msg="Querying source" name=telegraf_kernel_plugin_source
 
A 2020-02-24T22:05:03.766159057Z time="2020-02-24T22:05:03Z" level=info msg="Querying source" name=telegraf_processes_plugin_source
 
A 2020-02-24T22:05:03.813855648Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.813872575Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.815469264Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.815480947Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.815788745Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.815799713Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.821697473Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.824242591Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.824306011Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.824354171Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.824647665Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.824688911Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:05:03.825736522Z time="2020-02-24T22:05:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:06:02.286172151Z time="2020-02-24T22:06:02Z" level=info msg="Querying source" name="prometheus_source: http://10.x.x.x:x/api/v1/metrics/prometheus"
 
A 2020-02-24T22:06:03.732597351Z time="2020-02-24T22:06:03Z" level=info msg="not scraping sources from: prometheus_metrics_provider: https://kubernetes.default.svc.cluster.local:443/metrics. current leader: ip-10-162-220-238.us-west-2.compute.internal"
 
A 2020-02-24T22:06:03.732616662Z time="2020-02-24T22:06:03Z" level=info msg="Querying source" name="kubelet_summary:10.x.x.x:x”
 
A 2020-02-24T22:06:03.734211444Z time="2020-02-24T22:06:03Z" level=info msg="Data push complete" name=wavefront_sink
 
A 2020-02-24T22:06:03.734658002Z time="2020-02-24T22:06:03Z" level=info msg="Querying source" name=internal_stats_source
 
A 2020-02-24T22:06:03.734677076Z fatal error: concurrent map iteration and map write
 
A 2020-02-24T22:06:03.736910104Z 

A 2020-02-24T22:06:03.736916780Z goroutine 95 [running]:
 
A 2020-02-24T22:06:03.736928462Z runtime.throw(0x19eb0ab, 0x26)
 
A 2020-02-24T22:06:03.736940860Z 	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc000b5bc90 sp=0xc000b5bc60 pc=0x42f652
 
A 2020-02-24T22:06:03.736944913Z runtime.mapiternext(0xc000b5be40)
 
A 2020-02-24T22:06:03.736948490Z 	/usr/local/go/src/runtime/map.go:858 +0x579 fp=0xc000b5bd18 sp=0xc000b5bc90 pc=0x40f709
 
A 2020-02-24T22:06:03.736952066Z runtime.mapiterinit(0x174f160, 0xc000264d80, 0xc000b5be40)
 
A 2020-02-24T22:06:03.736979007Z 	/usr/local/go/src/runtime/map.go:848 +0x1c3 fp=0xc000b5bd38 sp=0xc000b5bd18 pc=0x40f0a3
 
A 2020-02-24T22:06:03.736983299Z github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/wavefront.(*wavefrontSink).send(0xc000263a00, 0xc000e58000)
 
A 2020-02-24T22:06:03.736986875Z 	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/wavefront/wavefront.go:140 +0x337 fp=0xc000b5beb0 sp=0xc000b5bd38 pc=0x14ddc67
 
A 2020-02-24T22:06:03.736990690Z github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/wavefront.(*wavefrontSink).ExportData(0xc000263a00, 0xc000e58000)
 
A 2020-02-24T22:06:03.736994266Z 	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/wavefront/wavefront.go:185 +0x60 fp=0xc000b5bed0 sp=0xc000b5beb0 pc=0x14de030
 
A 2020-02-24T22:06:03.737005710Z github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks.NewSinkManager.func1(0x1c77f80, 0xc000263a00, 0xc0000d0a80, 0xc0000d0ae0, 0xc0000d0b40)
 
A 2020-02-24T22:06:03.737009525Z 	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/manager.go:79 +0x274 fp=0xc000b5bfb8 sp=0xc000b5bed0 pc=0x15c9614
 
A 2020-02-24T22:06:03.737013101Z runtime.goexit()
 
A 2020-02-24T22:06:03.737020969Z 	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000b5bfc0 sp=0xc000b5bfb8 pc=0x45f031
 
A 2020-02-24T22:06:03.737024784Z created by github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks.NewSinkManager
 
A 2020-02-24T22:06:03.737028360Z 	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/manager.go:75 +0x214
 
A 2020-02-24T22:06:03.737038135Z 
 
A 2020-02-24T22:06:03.737041711Z goroutine 1 [select (no cases), 263 minutes]:
 
A 2020-02-24T22:06:03.737045049Z main.waitForStop()
 
A 2020-02-24T22:06:03.737052679Z 	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/cmd/wavefront-collector/main.go:467 +0x20
 
A 2020-02-24T22:06:03.737056493Z main.main()
 
A 2020-02-24T22:06:03.737059831Z 	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/cmd/wavefront-collector/main.go:86 +0x2d9
 
A 2020-02-24T22:06:03.737071514Z 
 
A 2020-02-24T22:06:03.737075090Z goroutine 18 [chan receive]:
 
A 2020-02-24T22:06:03.737078428Z github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x2b69f20)
 
A 2020-02-24T22:06:03.737091779Z 	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/klog/klog.go:1010 +0x8b
 
A 2020-02-24T22:06:03.737095594Z created by github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/klog.init.0
 
A 2020-02-24T22:06:03.737102031Z 	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/vendor/k8s.io/klog/klog.go:411 +0xd6
 
A 2020-02-24T22:06:03.737129926Z 
 
A 2020-02-24T22:06:03.737139225Z goroutine 81 [syscall, 263 minutes]:
 
A 2020-02-24T22:06:03.737143039Z os/signal.signal_recv(0x0)
 
A 2020-02-24T22:06:03.737146615Z 	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
 
A 2020-02-24T22:06:03.737150192Z os/signal.loop()
 
A 2020-02-24T22:06:03.737153768Z 	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
 
A 2020-02-24T22:06:03.737157344Z created by os/signal.init.0
 
A 2020-02-24T22:06:03.737162590Z 	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
 
```

**Comment by ltagliamonte-dd** [comment]
seeing the same issue on 1.0.9 as well

**Comment by vgunapati** [comment]
This problem is still present in the latest release 

```
fatal error: concurrent map iteration and map write
goroutine 50 [running]:
runtime.throw(0x190f5b3, 0x26)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0001bec78 sp=0xc0001bec48 pc=0x437712
runtime.mapiternext(0xc0001bed70)
	/usr/local/go/src/runtime/map.go:853 +0x554 fp=0xc0001becf8 sp=0xc0001bec78 pc=0x410e94
github.com/wavefronthq/wavefront-collector-for-kubernetes/internal/metrics.(*MetricPoint).GetTags(0xc0000bbb60, 0x0)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/internal/metrics/types.go:205 +0x1b0 fp=0xc0001bedf0 sp=0xc0001becf8 pc=0xb770d0
github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/wavefront.(*wavefrontSink).send(0xc00042ac00, 0xc000894400)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/wavefront/wavefront.go:207 +0x125 fp=0xc0001beeb0 sp=0xc0001bedf0 pc=0x146f685
github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/wavefront.(*wavefrontSink).ExportData(0xc00042ac00, 0xc000894400)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/wavefront/wavefront.go:228 +0x35 fp=0xc0001beed0 sp=0xc0001beeb0 pc=0x146f915
github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks.NewSinkManager.func1(0x1affe80, 0xc00042ac00, 0xc000204cc0, 0xc000204d20, 0xc000204d80)
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/manager.go:79 +0x296 fp=0xc0001befb8 sp=0xc0001beed0 pc=0x155e3d6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0001befc0 sp=0xc0001befb8 pc=0x46f5c1
created by github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks.NewSinkManager
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/plugins/sinks/manager.go:75 +0x21c
goroutine 1 [select (no cases), 160 minutes]:
main.waitForStop()
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/cmd/wavefront-collector/main.go:466 +0x25
main.main()
	/go/src/github.com/wavefronthq/wavefront-collector-for-kubernetes/cmd/wavefront-collector/main.go:85 +0x2d1
```

**Comment by josephgee** [comment]
Is this issue still being seen in 1.5.0 or later? If so, could we have some more information on how to reproduce it? We are not seeing it.
